### ISSUE TITLE
Documentation build is suddenly failing

### ISSUE THREAD

**Issue by n-claes** [n-claes/legolas#101]
## Issue description
After a recent push to one of the development branches the docs are suddenly failing:
```
Traceback (most recent call last):
[8](https://github.com/n-claes/legolas/runs/7408674995?check_suite_focus=true#step:5:9)
  File "/opt/hostedtoolcache/Python/3.9.13/x64/bin/ford", line 8, in <module>
[9](https://github.com/n-claes/legolas/runs/7408674995?check_suite_focus=true#step:5:10)
    sys.exit(run())
[10](https://github.com/n-claes/legolas/runs/7408674995?check_suite_focus=true#step:5:11)
  File "/opt/hostedtoolcache/Python/3.9.13/x64/lib/python3.9/site-packages/ford/__init__.py", line 633, in run
[11](https://github.com/n-claes/legolas/runs/7408674995?check_suite_focus=true#step:5:12)
    proj_data, proj_docs, md = initialize()
[12](https://github.com/n-claes/legolas/runs/7408674995?check_suite_focus=true#step:5:13)
  File "/opt/hostedtoolcache/Python/3.9.13/x64/lib/python3.9/site-packages/ford/__init__.py", line 236, in initialize
[13](https://github.com/n-claes/legolas/runs/7408674995?check_suite_focus=true#step:5:14)
    return parse_arguments(vars(args), proj_docs, directory)
[14](https://github.com/n-claes/legolas/runs/7408674995?check_suite_focus=true#step:5:15)
  File "/opt/hostedtoolcache/Python/3.9.13/x64/lib/python3.9/site-packages/ford/__init__.py", line 406, in parse_arguments
[15](https://github.com/n-claes/legolas/runs/7408674995?check_suite_focus=true#step:5:16)
    md = markdown.Markdown(
[16](https://github.com/n-claes/legolas/runs/7408674995?check_suite_focus=true#step:5:17)
  File "/opt/hostedtoolcache/Python/3.9.13/x64/lib/python3.9/site-packages/markdown/core.py", line 96, in __init__
[17](https://github.com/n-claes/legolas/runs/7408674995?check_suite_focus=true#step:5:18)
    self.registerExtensions(extensions=kwargs.get('extensions', []),
[18](https://github.com/n-claes/legolas/runs/7408674995?check_suite_focus=true#step:5:19)
  File "/opt/hostedtoolcache/Python/3.9.13/x64/lib/python3.9/site-packages/markdown/core.py", line 125, in registerExtensions
[19](https://github.com/n-claes/legolas/runs/7408674995?check_suite_focus=true#step:5:20)
    ext.extendMarkdown(self)
[20](https://github.com/n-claes/legolas/runs/7408674995?check_suite_focus=true#step:5:21)
TypeError: extendMarkdown() missing 1 required positional argument: 'md_globals'
```

This seems to be an upstream issue with Ford, not immediately sure how to fix this...

**Comment by n-claes** [comment]
Temporarily fixed this in #98 by capping the markdown version through
```
pip install markdown==3.3.7
```
before installing ford. While far from ideal this works for now...

Keeping this open as a reminder to put back the defaults when upstream is fixed.
