### ISSUE TITLE
Pylbo: cannot retrieve eigenfunctions in merged spectra if datfile contains only 1 eigenvalue

### ISSUE THREAD

**Issue by jordidj** [n-claes/legolas#109]
## Issue description
When using `plot_merged_spectrum` in combination with `add_eigenfunctions` to combine datfiles with only 1 eigenvalue, the eigenfunctions cannot be displayed due to an index error.

## Bug report
**Minimal example for reproduction**
The passed argument is a folder path to a folder containing datfiles with a single eigenvalue and its associated eigenfunctions.
```
from os import listdir
import pylbo
import argparse as ap

parser = ap.ArgumentParser()
parser.add_argument('-i', required=True, action='store', dest='i', help='followed by file path')
parser.add_argument('-ef', action='store_true', default=False, help='show eigenfunctions')
args = parser.parse_args()

files = listdir(args.i)
for ix in range(len(files)):
    files[ix] = args.i + files[ix]
files.sort()

series = pylbo.load_series(files)
p = pylbo.plot_merged_spectrum(series)
if args.ef:
    p.add_eigenfunctions()
p.show()
```

**Actual result**
```
Traceback (most recent call last):
  File "/home/jordi/anaconda3/envs/legolas/lib/python3.8/site-packages/matplotlib/cbook/__init__.py", line 287, in process
    func(*args, **kwargs)
  File "/home/jordi/codes/legolas/post_processing/pylbo/visualisation/eigenfunction_interface.py", line 174, in on_point_pick
    self.on_left_click(event)
  File "/home/jordi/codes/legolas/post_processing/pylbo/visualisation/eigenfunction_interface.py", line 219, in on_left_click
    idx, xdata, ydata = self._get_clicked_point_data(event)
  File "/home/jordi/codes/legolas/post_processing/pylbo/visualisation/eigenfunction_interface.py", line 299, in _get_clicked_point_data
    return idx, xdata[idx], ydata[idx]
  File "/home/jordi/anaconda3/envs/legolas/lib/python3.8/site-packages/numpy/ma/core.py", line 3222, in __getitem__
    dout = self.data[indx]
IndexError: too many indices for array: array is 0-dimensional, but 1 were indexed
```

**Expected result**
Display of the eigenfunctions of the requested mode.

**Version info**
- Legolas version: 1.2.1
- Pylbo version: 1.1.3
- Python version: 3.8.13
- Version of relevant libraries (matplotlib, numpy, etc.): matplotlib 3.5.3, numpy 1.23.3

**Comment by n-claes** [comment]
Should be fixed in #119
